name: Manual Artist Fetch

on:
  workflow_dispatch:  

permissions:
  contents: write

jobs:
  run-fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Commit and Push
        run: |
          # ... git config ...
          git add artists_id.txt
          git commit -m "Manual update"
          git push origin HEAD:dev

          
